name: Test Actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Make a file
        run: mkdir share/spack -p && touch share/spack/setup-env.sh
      - name: Set color
        id: random-color-generator
        run: echo "SELECTED_COLOR=`realpath share/spack/setup-env.sh`" >> "$GITHUB_OUTPUT"
      - name: Get color
        run: echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"
      - name: Test if in GH Action
        run: if [[ -z "$GITHUB_ACTIONS" ]]; then echo "GH Action speaking!" fi

